//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_of_sale_system.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ID { get; set; }
        public string Expensefor { get; set; }
        public System.DateTime Today_Date { get; set; }
        public double Amount { get; set; }
        public string ReferenceNo { get; set; }
        public string Note { get; set; }
        public int CategoryID { get; set; }
    
        public virtual ExpenseCategory ExpenseCategory { get; set; }
    }
}
